import { createClient } from 'jsr:@supabase/supabase-js@2';
import Stripe from 'npm:stripe@22.4.0';
import { CATALOGUE, CORS, cleanEmail, json, normalise, totalFor } from '../_shared/catalogue.ts';

/**
 * Opens a checkout: a draft order and a PaymentIntent to pay it with.
 *
 * Mirrors the Funnel Engine flow that has actually processed money — draft
 * order, PaymentIntent, client confirms, webhook fulfils — with two deliberate
 * modernisations:
 *
 * 1. **`payment_method_types` is never sent.** Omitting it turns on dynamic
 *    payment methods, so Stripe picks what to show from the buyer's device,
 *    country and amount. That is what makes **Apple Pay and Google Pay appear
 *    by themselves** inside the Payment Element — Funnel Engine needed a
 *    separate Payment Request Button mounted above the email field to get the
 *    same thing, and that button has to be kept in sync with the bump total by
 *    hand. One fewer surface, and one fewer way for the wallet total to
 *    disagree with the card total.
 *
 * 2. **Payment Element, not the legacy Card Element**, which is what the
 *    dynamic methods render into.
 *
 * ### The two rules that keep this honest
 * - **The amount is computed here, from the catalogue.** The client sends a
 *   selection of add-on slugs. A checkout that accepts a price from the browser
 *   sells the product for one cent to anyone who opens the network tab.
 * - **The order is created `draft`.** Only the webhook marks it paid. The
 *   client is the one party in this transaction with a motive to lie about
 *   whether money moved.
 *
 * `setup_future_usage: 'off_session'` is what makes the one-click upsell
 * possible: the card is saved with the purchase, so accepting a Partner Seat
 * thirty seconds later charges without re-entry.
 */

const stripe = new Stripe(Deno.env.get('STRIPE_SECRET_KEY') ?? '', {
  apiVersion: '2026-07-29.dahlia',
  // Deno has no Node http stack; without this the SDK cannot make requests.
  httpClient: Stripe.createFetchHttpClient(),
});

const admin = createClient(
  Deno.env.get('SUPABASE_URL') ?? '',
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
);

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS });
  if (req.method !== 'POST') return json({ error: 'method_not_allowed' }, 405);

  let body: {
    email?: unknown;
    addons?: unknown;
    partnerEmail?: unknown;
    // Meta identity, captured HERE because the Stripe webhook that fires the
    // Purchase event has no browser to read cookies from.
    fbp?: unknown;
    fbc?: unknown;
    eventId?: unknown;
    sourceUrl?: unknown;
  };
  try {
    body = await req.json();
  } catch {
    return json({ error: 'bad_request' }, 400);
  }

  const email = cleanEmail(body.email);
  if (!email) return json({ error: 'bad_email' }, 400);

  // `core` is always part of a checkout; the bump is the only thing the client
  // can add here. Upsells are charged later, off-session.
  const selection = normalise(['core', ...(Array.isArray(body.addons) ? body.addons : [])]).filter(
    (s) => CATALOGUE[s].slot === 'core' || CATALOGUE[s].slot === 'bump',
  );
  const amount = totalFor(selection);
  if (amount <= 0) return json({ error: 'empty_order' }, 400);

  const partnerEmail = cleanEmail(body.partnerEmail);

  /**
   * The tracking identity, taken from the request rather than the body where
   * possible — a browser cannot lie about the IP it connected from or the user
   * agent it sent, and both are match signals Meta weighs.
   */
  const str = (v: unknown, max = 400) =>
    typeof v === 'string' && v.length > 0 ? v.slice(0, max) : null;
  const tracking = {
    fbp: str(body.fbp, 120),
    fbc: str(body.fbc, 255),
    // Cloudflare/Supabase put the real client IP here; the socket address is
    // the edge node's and would match nobody.
    client_ip:
      req.headers.get('cf-connecting-ip') ??
      req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ??
      null,
    client_ua: req.headers.get('user-agent'),
    event_source_url: str(body.sourceUrl, 500),
    // Generated by the browser and shared with its own Purchase pixel, so Meta
    // counts one conversion instead of two.
    purchase_event_id: str(body.eventId, 120) ?? crypto.randomUUID(),
  };

  try {
    /**
     * Reuse the Stripe customer for this email if there is one.
     *
     * Retrieve-first, exactly as Funnel Engine does, and for the same reason:
     * a customer id created in test mode is meaningless in live mode, and the
     * "No such customer" that follows a mode switch fails the checkout of a
     * real buyer. Searching by email rather than storing an id means the two
     * modes simply never see each other's customers.
     */
    const existing = await stripe.customers.list({ email, limit: 1 });
    const customer =
      existing.data[0] ?? (await stripe.customers.create({ email, metadata: { app: 'dayspine' } }));

    /**
     * Reuse an open PaymentIntent for the same buyer and the same basket.
     *
     * Funnel Engine calls this duplicate-order prevention. Without it, a form
     * resubmit, a network retry or a double-tap creates a second intent — and
     * two intents against one card is how a customer ends up charged twice for
     * a lifetime licence they can only own once.
     */
    const { data: open } = await admin
      .from('orders')
      .select('id, stripe_payment_intent_id, amount_cents, items')
      .eq('email', email)
      .eq('status', 'draft')
      .order('created_at', { ascending: false })
      .limit(1);

    const reusable = open?.[0];
    if (reusable?.stripe_payment_intent_id) {
      const intent = await stripe.paymentIntents.retrieve(reusable.stripe_payment_intent_id);
      const sameBasket =
        reusable.amount_cents === amount &&
        JSON.stringify([...(reusable.items ?? [])].sort()) === JSON.stringify([...selection].sort());

      // Only reuse an intent that is still payable. A `succeeded` or `canceled`
      // one must never be handed back — the first would show a paid order as
      // unpaid, the second would fail confirmation with no explanation.
      if (sameBasket && ['requires_payment_method', 'requires_confirmation'].includes(intent.status)) {
        return json(
          { clientSecret: intent.client_secret, orderId: reusable.id, amount, items: selection },
          200,
        );
      }
    }

    const { data: order, error: orderError } = await admin
      .from('orders')
      .insert({
        email,
        status: 'draft',
        items: selection,
        amount_cents: amount,
        stripe_customer_id: customer.id,
        partner_email: partnerEmail,
        ...tracking,
      })
      .select('id')
      .single();

    if (orderError || !order) {
      console.error('order insert failed:', orderError?.message);
      return json({ error: 'order_failed' }, 500);
    }

    const intent = await stripe.paymentIntents.create({
      amount,
      currency: 'usd',
      customer: customer.id,
      receipt_email: email,
      // ⭐ Saves the card so the upsell can be one click. Without it the buyer
      // re-enters a card thirty seconds after paying, and almost nobody does.
      setup_future_usage: 'off_session',
      // ⭐ NOT setting `payment_method_types` is what enables Apple Pay, Google
      // Pay and Link. Naming 'card' here would silently disable all of them.
      metadata: {
        order_id: order.id,
        app: 'dayspine',
        items: selection.join(','),
        partner_email: partnerEmail ?? '',
      },
    });

    await admin
      .from('orders')
      .update({ stripe_payment_intent_id: intent.id, updated_at: new Date().toISOString() })
      .eq('id', order.id);

    return json(
      { clientSecret: intent.client_secret, orderId: order.id, amount, items: selection },
      200,
    );
  } catch (e) {
    // Never echo the Stripe message to the browser: it can name the account,
    // the customer, or why a specific card failed.
    console.error('create-checkout failed:', e instanceof Error ? e.message : e);
    return json({ error: 'checkout_failed' }, 500);
  }
});
